language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t tariqbeans/cbk-demo -f Dockerfile .

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "cbk-demo"
    env: "CbkDemo-env"
    bucket_name: "elasticbeanstalk-eu-west-3-066550581276"
    bucket_path: "cbk-demo"
    
    on:
        brach: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY



